package com.greenbridge.system;// Generated by Selenium IDE
import com.greenbridge.GreenBridgeApplication;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.runner.RunWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment =SpringBootTest.WebEnvironment.DEFINED_PORT, classes = GreenBridgeApplication.class)
public class TF4 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC41() {
    driver.get("http://localhost:8080/home");
    driver.manage().window().setSize(new Dimension(1428, 810));
    try {
      driver.findElement(By.cssSelector("button > img")).click();
      driver.findElement(By.id("input")).click();
      driver.findElement(By.id("input")).sendKeys("stat");
      driver.findElement(By.id("input")).sendKeys(Keys.ENTER);

      driver.findElement(By.id("sendButton")).click();
      {
        List<WebElement> elements = driver.findElements(By.cssSelector("#chat > .messages__item--visitor"));
        assert (elements.size() > 0);
      }
    }catch (Exception e) {
    }
    driver.close();
    }


  @Test
  public void tC42() {
    driver.get("http://localhost:8080/home");
    driver.manage().window().setSize(new Dimension(1428, 810));
    try {
    driver.findElement(By.cssSelector("button > img")).click();
    driver.findElement(By.id("input")).click();
    driver.findElement(By.id("input")).sendKeys("/start");
    driver.findElement(By.id("input")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("sendButton")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#chat > .messages__item--visitor"));
      assert(elements.size() > 0);
    }
    }catch (Exception e) {
    }
    driver.close();
  }
}
