package com.greenbridge.system;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static java.lang.Thread.sleep;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TF4 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void tC41() throws InterruptedException {
        sleep(5000);
        driver.get("http://127.0.0.1:8080/");
        driver.manage().window().setSize(new Dimension(1428, 810));
        driver.findElement(By.cssSelector("button > img")).click();
        driver.findElement(By.id("input")).click();
        driver.findElement(By.id("input")).sendKeys("stat");
        driver.findElement(By.id("input")).sendKeys(Keys.ENTER);
        //driver.close();
    }
    @Test
    public void tC42() {
        driver.get("http://127.0.0.1:8080/");
        driver.manage().window().setSize(new Dimension(1428, 810));
        driver.findElement(By.cssSelector("button > img")).click();
        driver.findElement(By.id("input")).click();
        driver.findElement(By.id("input")).sendKeys("/start");
        driver.findElement(By.id("input")).sendKeys(Keys.ENTER);
        //driver.close();
    }
}
