package com.greenbridge.system;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.HashMap;
import java.util.Map;

import static java.lang.Thread.sleep;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
public class TF5 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws InterruptedException {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://localhost:8080/login");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("fernandaiannuzzi@example.org");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("yBmaNPq%Qw!v5C2r");
    driver.findElement(By.cssSelector(".inputButton")).click();
    sleep(2000);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC3() {
    driver.get("http://localhost:8080/recensione/3");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector("label:nth-child(6)")).click();
    driver.findElement(By.id("testo-recensione")).click();
    driver.findElement(By.id("testo-recensione")).sendKeys("Davvero una bella banana");
    driver.findElement(By.name("Fine")).click();
    assertThat(driver.getCurrentUrl(), is("http://localhost:8080/saveRecensione"));

  }
  @Test
  public void tC2() {
    driver.get("http://localhost:8080/recensione/3");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector("label:nth-child(6)")).click();
    driver.findElement(By.id("testo-recensione")).click();
    driver.findElement(By.id("testo-recensione")).sendKeys("La banana è un frutto eccezionale che offre non solo un gusto delizioso, dolce e cremoso, ma anche numerosi benefici per la salute. La sua consistenza morbida e la facilità con cui può essere consumata la rendono una scelta ideale per uno spuntino veloce o come ingrediente in varie ricette. Ricca di potassio, vitamine e fibre, la banana favorisce la salute cardiaca, regola la pressione sanguigna e migliora la digestione. La sua versatilità la rende adatta a essere utilizzata in frullati, dessert, pancake e molto altro. Inoltre, il suo involucro naturale la rende una scelta ecologica e pratica. La banana è un frutto irresistibile che soddisfa il palato e promuove il benessere complessivo.");
    driver.findElement(By.name("Fine")).click();
    assertThat(driver.switchTo().alert().getText(), is("Descrizione troppo lunga!"));
  }
  @Test
  public void tC1() {
    driver.get("http://localhost:8080/recensione/3");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.name("Fine")).click();
    assertThat(driver.switchTo().alert().getText(), is("Voto non inserito!"));
  }
}