package com.greenbridge.system;// Generated by Selenium IDE
import com.greenbridge.GreenBridgeApplication;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.junit.runner.RunWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.*;

@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment =SpringBootTest.WebEnvironment.DEFINED_PORT, classes = GreenBridgeApplication.class)
public class TF7 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC71() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.id("searchBar")).click();
    driver.findElement(By.id("searchButton")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il campo di ricerca non può essere vuoto"));
  }

  @Test
  public void tC72() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.id("searchBar")).click();
    driver.findElement(By.id("searchBar")).sendKeys("sdhiasdhbiasjkdnksandkoasndoaspndaskopndkasndlasndkasndklasndlasdlkds");
    driver.findElement(By.id("searchButton")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il prodotto inserito è troppo lungo"));
  }

  @Test
  public void tC73() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.id("searchBar")).click();
    driver.findElement(By.id("searchBar")).sendKeys("@ciao!");
    driver.findElement(By.id("searchButton")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il formato dell\'input non è valido. Utilizza solo lettere, spazi, apostrofi e trattini, da 1 a 50 caratteri."));
  }

  @Test
  public void tC74() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.id("searchBar")).click();
    driver.findElement(By.id("searchBar")).sendKeys("APPL");
    driver.findElement(By.id("searchButton")).click();
    driver.findElement(By.linkText("Dettagli")).click();
  }
}
